name: testing github actions
on:
  workflow_dispatch:

jobs:
  first_job:
    runs-on: ubuntu-latest   
    steps:
      - name: Checkout code  
        uses: actions/checkout@main
        
      - name: Welcome and list files
        run: |
          echo "learning the gh actions using BGT"
          ls -lahrt
          echo "Bumrah should be the captain!!!"
          cat README.md

      - name: Install the cowsay program
        run: sudo apt-get install cowsay -y

      - name: Excecute cowsay CMD
        run: cowsay -f dragon "Run..run..run benchod..DRAGON...bhag saale" >> dragon.txt

      - name: Find the drgon file
        run:  grep -i "dragon" dragon.txt 

      - name: read file
        run: cat dragon.txt

      - name: say tata
        run: echo "Tata..bye-bye see you..!!!"
        

